### ISSUE TITLE
Block 11/18 issue in instagrab.ipynb

### ISSUE THREAD

**Issue by rbeaupre** [pwikstrom/build-a-bot#1]
Executing block 18 gets me nowhere... 17 will initialize Firefox but the driver never seems to even try to fetch instagram.com.

Any ideas why?

**Comment by rbeaupre** [comment]
Geckodriver for winx64 log file:

`1512584551915	geckodriver	INFO	Listening on 127.0.0.1:51024
1512584553955	mozprofile::profile	INFO	Using profile path C:\Users\MSI_USER\AppData\Local\Temp\rust_mozprofile.cG7HRgOA6q4H
1512584553963	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1512584554025	geckodriver::marionette	INFO	Connecting to Marionette on localhost:51030
Unable to read VR Path Registry from C:\Users\MSI_USER\AppData\Local\openvr\openvrpaths.vrpath
[Parent 7016, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\MSI_USER\AppData\Local\openvr\openvrpaths.vrpath
[Child 4876, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4876, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 7016, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 7016, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\MSI_USER\AppData\Local\openvr\openvrpaths.vrpath
[Child 10072, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 10072, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\MSI_USER\AppData\Local\openvr\openvrpaths.vrpath
[Child 6820, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6820, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\MSI_USER\AppData\Local\openvr\openvrpaths.vrpath
[GPU 6764, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv`

**Comment by twhipp** [comment]
I had the same issue, then I dropped Firefox into the instagram folder I created and it worked.  However, once I went to send the keystrokes down the page I recieved an error.  Have you gotten past that part?  I was unsure if perhaps IG changed the class names on the load more button or that feature was no longer able to be accessed outside of the API?

**Comment by rbeaupre** [comment]
Yeah, I got it to work by updating the driver and re-installing firefox. 

However, I'm stuck at the keystrokes as well. The class on instagram's load more button did change (you can see that it's '_1cr2e _epyes' now) but even after I changed it to reflect that it wouldn't work.

I think it might have to do with the fact that, when you're not logged in, you only need to press 'load more' once before it comes infinite scroll. And when you're logged in, it's just always infinite scroll...

![image](https://user-images.githubusercontent.com/24485850/33730126-08a23fa4-db4d-11e7-8029-7153f0b2a6d2.png)

**Comment by rbeaupre** [comment]
I can confirm that "1cr2e" works if you set it as the new class to find in block 11 (the keystrokes section).
